default: &default
  host: localhost #<%= `ip route | awk '/default/ { print $3 }'`.strip %>
  port: 5433
  username: <%= Rails.application.credentials.dig(:database, :user) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsnew_dev

test:
  <<: *default
  database: railsnew_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: railsnew_production
    migrations_paths: db/migrate

  queue:
    <<: *primary_production
    url: <%= ENV['CABLE_DATABASE_URL'] %>
    database: railsnew_production_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *primary_production
    url: <%= ENV['CACHE_DATABASE_URL'] %>
    database: railsnew_production_cache
    migrations_paths: db/cache_migrate
  
  cable:
    <<: *primary_production
    url: <%= ENV['CABLE_DATABASE_URL'] %>
    database: railsnew_production_cable
    migrations_paths: db/cable_migrate